apiVersion: v1
kind: Pod
metadata:
  name: node-selector-2
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    disktype: ssd
  tolerations: 
    - key: "key1"
      value: "value1"
      operator: "equal"
      effect: "NoSchedule"
    - key: "key1"
      value: "value1"
      operator: "equal"
      effect: "NoExecute"     